import { Archivo_Black, Roboto } from 'next/font/google';
import './globals.css';
import Nav from './_components/nav/page';
import ReactQueryProvider from './_components/reactQueryProvider/page';
import { UserProvider } from '@/context/useContext';
import { Toaster } from 'react-hot-toast';
import Footer from './_components/footer/page';
import SessionProviderWrapper from './_components/sessionProvide/page';
import AuthProvider from '@/context/useAuth';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const archivoText = Archivo_Black({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-archivo',
});

const robotoText = Roboto({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-roboto',
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      dir="ltr"
      className={`${archivoText.variable} ${robotoText.variable}`}
    >
      <head>
        <title>e-commerce website</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="bg-white max-w-[1300px] mx-auto ">
        <SessionProviderWrapper>
          <ReactQueryProvider>
            <AuthProvider>
              <UserProvider>
                <Toaster />
                <header>
                  <Nav />
                </header>
                <main className="lg:min-h-screen">{children}</main>
                <footer>
                  <Footer />
                </footer>
              </UserProvider>
            </AuthProvider>
          </ReactQueryProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
