import { Archivo_Black, Roboto } from 'next/font/google';
import './globals.css';
import Nav from './_components/nav/page';
import ReactQueryProvider from './_components/reactQueryProvider/page';
import { UserProvider } from '@/context/useContext';
import { Toaster } from 'react-hot-toast';
import Footer from './_components/footer/page';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const archivoText = Archivo_Black({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-archivo',
});

const robotoText = Roboto({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-roboto',
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${archivoText.variable} ${robotoText.variable}`}
    >
      <body className="bg-white max-w-[1300px] mx-auto ">
        <ReactQueryProvider>
          <UserProvider>
            <Toaster />
            <header>
              <Nav />
            </header>
            <main className="min-h-screen">{children}</main>
            <footer>
              <Footer />
            </footer>
          </UserProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
